# Generated by Django 5.0.dev20230218152810 on 2023-02-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_itemdemenu_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdemenu',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='itemdemenu',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
