# Generated by Django 5.0.dev20230218152810 on 2023-02-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_itemdemenu_disponivel_itemdemenu_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdemenu',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
