# Generated by Django 5.0.dev20230218152810 on 2023-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_itemdemenu_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelopedido',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='modelopedido',
            name='qtd',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
