# Generated by Django 5.0.dev20230218152810 on 2023-02-26 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_modelopedido_data_criacao_modelopedido_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopedido',
            name='data_criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
