# Generated by Django 5.0.dev20230218152810 on 2023-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_modelopedido_data_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
