# Generated by Django 5.0.dev20230218152810 on 2023-02-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_modelopedido_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopedido',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
